Object.init = function() {};
Object.result = function() {};
Object.step = function() {};
Object.next = function() {};
Object.value;
Object.done;
var define = function() {};
var transducers = {};
transducers.reduced = function() {};
transducers.isReduced = function() {};
transducers.comp = function() {};
transducers.complement = function() {};
transducers.map = function() {};
transducers.filter = function() {};
transducers.remove = function() {};
transducers.keep = function() {};
transducers.keepIndexed = function() {};
transducers.cat = function() {};
transducers.mapcat = function() {};
transducers.transduce = function() {};
transducers.reduce = function() {};
transducers.take = function() {};
transducers.takeWhile = function() {};
transducers.takeNth = function() {};
transducers.drop = function() {};
transducers.dropWhile = function() {};
transducers.partitionBy = function() {};
transducers.partitionAll = function() {};
transducers.into = function() {};
transducers.completing = function() {};
transducers.toFn = function() {};
transducers.wrap = function() {};
transducers.first = function() {};
transducers.ensureReduced = function() {};
transducers.unreduced = function() {};

